name: Deploy Python package to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create deployment package
      run: |
        # 必要なファイルのみをデプロイメントディレクトリにコピー
        mkdir deployment
        cp app.py deployment/
        cp -r app deployment/
        cp requirements.txt deployment/
        cp startup.sh deployment/
        cp -r data deployment/
        cp .deployment deployment/
        
        # 権限の設定
        chmod +x deployment/startup.sh
        
        # デプロイメントパッケージの作成
        cd deployment
        zip -r ../package.zip ./*

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tech0-gen-8-step3-testapp-py2-26'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package.zip